gii-is-DP1/dp1-2020-g3-11

src/main/java/org/springframework/samples/petclinic/model/Entrada.java
src/main/java/org/springframework/samples/petclinic/model/Festival.java
src/main/java/org/springframework/samples/petclinic/model/Puesto.java
src/main/java/org/springframework/samples/petclinic/model/Recinto.java
src/main/java/org/springframework/samples/petclinic/model/Valoracion.java
src/main/java/org/springframework/samples/petclinic/web/AboutController.java
src/main/resources/db/hsqldb/data.sql
src/main/webapp/WEB-INF/jsp/about.jsp
src/main/webapp/WEB-INF/tags/menu.tag

Campos eran -> Asociaciones onetomany, manytone desde puesto,recinto,entrada,valoración y  festival. Base de datos poblada correctamente.

Agregar campos a entidades y crear vista about.jsp 11/11/2020

---

src/main/java/org/springframework/samples/petclinic/model/Entrada.java
src/main/java/org/springframework/samples/petclinic/model/EntradaType.java
src/main/java/org/springframework/samples/petclinic/model/TipoEntrada.java
src/main/java/org/springframework/samples/petclinic/model/Usuario.java
src/main/java/org/springframework/samples/petclinic/repository/EntradaRepository.java
src/main/java/org/springframework/samples/petclinic/service/EntradaService.java
src/main/java/org/springframework/samples/petclinic/web/EntradaController.java
src/main/java/org/springframework/samples/petclinic/web/EntradaValidator.java
src/main/resources/db/hsqldb/data.sql
src/main/webapp/WEB-INF/jsp/entradas/createOrUpdateEntradaForm.jsp
src/main/webapp/WEB-INF/jsp/entradas/entradaListing.jsp

creación, edición, borrado y listado de entradas de un

---

src/test/java/org/springframework/samples/petclinic/service/ArtistServiceTests.java

Pruebas restantes: Edit +, Edit -, delete

Pruebas de Servicio Artista

---

src/main/java/org/springframework/samples/petclinic/model/Festival.java
src/main/java/org/springframework/samples/petclinic/web/ArtistaValidator.java
src/main/java/org/springframework/samples/petclinic/web/EntradaController.java
src/main/java/org/springframework/samples/petclinic/web/EntradaValidator.java
src/main/java/org/springframework/samples/petclinic/web/FestivalController.java
src/main/java/org/springframework/samples/petclinic/web/FestivalValidator.java
src/main/java/org/springframework/samples/petclinic/web/RecintoValidator.java
src/main/webapp/WEB-INF/jsp/festivales/createOrUpdateFestivalForm.jsp

21/11 - Añadir validaciones a Festival, correción y mejora de otras

---

src/main/java/org/springframework/samples/petclinic/model/Recinto.java
src/main/webapp/WEB-INF/jsp/festivales/createOrUpdateFestivalForm.jsp
src/test/java/org/springframework/samples/petclinic/model/FestivalValidatorTest.java
src/test/java/org/springframework/samples/petclinic/model/RecintoValidatorTest.java

Añadir pruebas restantes y revisión app

---

src/main/java/org/springframework/samples/petclinic/model/Festival.java
src/main/java/org/springframework/samples/petclinic/web/ArtistaValidator.java
src/main/java/org/springframework/samples/petclinic/web/FestivalValidator.java
src/main/java/org/springframework/samples/petclinic/web/RecintoValidator.java

Mejora validaciones (artista,festi) Sprint 3

Mejora validaciones (artista,festi) Sprint 3

---

src/main/java/org/springframework/samples/petclinic/model/Puesto.java
src/main/java/org/springframework/samples/petclinic/model/Recinto.java
src/main/java/org/springframework/samples/petclinic/model/TipoPuesto.java
src/main/java/org/springframework/samples/petclinic/model/TipoTamaño.java
src/main/java/org/springframework/samples/petclinic/repository/PuestoRepository.java
src/main/java/org/springframework/samples/petclinic/repository/RecintoRepository.java
src/main/java/org/springframework/samples/petclinic/service/PuestoService.java
src/main/java/org/springframework/samples/petclinic/service/RecintoService.java
src/main/java/org/springframework/samples/petclinic/web/PuestoController.java
src/main/java/org/springframework/samples/petclinic/web/RecintoController.java
src/main/resources/db/hsqldb/data.sql
src/main/webapp/WEB-INF/jsp/festivales/vistaFestival.jsp
src/main/webapp/WEB-INF/jsp/puestos/createOrUpdatePuestoForm.jsp
src/main/webapp/WEB-INF/jsp/puestos/puestosListing.jsp
src/main/webapp/WEB-INF/jsp/recintos/createOrUpdateRecintoForm.jsp
src/main/webapp/WEB-INF/jsp/recintos/detallesRecinto.jsp
src/test/java/org/springframework/samples/petclinic/service/ConcertServiceTests.java
src/test/java/org/springframework/samples/petclinic/service/FestivalServiceTest.java
src/test/java/org/springframework/samples/petclinic/service/RecintoServiceTests.java

funcionalidades de puestos (Alejandro Manzano y Pablo Santos)

Corregido los errores de navegación entre vistas y añadido

---

src/main/resources/db/hsqldb/data.sql
src/main/webapp/WEB-INF/jsp/festivales/festivalListing.jsp

Fix de valoración y name de festival linked en user y sponsor.

Fix de añadir valoración y de vista lista festival, botones name.

---

src/main/java/org/springframework/samples/petclinic/model/Oferta.java
src/main/java/org/springframework/samples/petclinic/model/Opinion.java
src/main/resources/db/hsqldb/data.sql
src/test/java/org/springframework/samples/petclinic/model/OfertaValidatorTest.java
src/test/java/org/springframework/samples/petclinic/model/OpinionValidatorTest.java
src/test/java/org/springframework/samples/petclinic/service/FestivalServiceTest.java
src/test/java/org/springframework/samples/petclinic/service/OfertaServiceTests.java
src/test/java/org/springframework/samples/petclinic/service/OpinionServiceTests.java

Pruebas de oferta y opinion // toqueteo a bbdd

Pruebas modelo y servicio - Opinion/oferta (+bbdd)

---

src/main/java/org/springframework/samples/petclinic/model/Entrada.java
src/main/java/org/springframework/samples/petclinic/model/Oferta.java
src/main/java/org/springframework/samples/petclinic/service/OfertaService.java
src/main/java/org/springframework/samples/petclinic/web/EntradaValidator.java
src/main/java/org/springframework/samples/petclinic/web/OfertaController.java
src/main/java/org/springframework/samples/petclinic/web/OfertaValidator.java

Validacion oferta y fix en entrada

---

src/main/java/org/springframework/samples/petclinic/model/Entrada.java
src/main/java/org/springframework/samples/petclinic/model/Oferta.java
src/main/java/org/springframework/samples/petclinic/model/Usuario.java
src/main/java/org/springframework/samples/petclinic/repository/OfertaRepository.java
src/main/java/org/springframework/samples/petclinic/web/EntradaController.java
src/main/resources/db/hsqldb/data.sql
src/main/webapp/WEB-INF/jsp/entradas/entradaComprada.jsp
src/test/java/org/springframework/samples/petclinic/model/EntradaValidatorTest.java
src/test/java/org/springframework/samples/petclinic/service/OfertaServiceTests.java

Asociar entrada y oferta y fix de usuario y entrada

Asociar entrada y oferta, fix de entrada y usuario

---

src/main/java/org/springframework/samples/petclinic/model/Entrada.java
src/main/java/org/springframework/samples/petclinic/model/User.java
src/main/java/org/springframework/samples/petclinic/model/Usuario.java
src/main/java/org/springframework/samples/petclinic/repository/UsuarioRepository.java
src/main/java/org/springframework/samples/petclinic/service/UsuarioService.java
src/main/java/org/springframework/samples/petclinic/web/EntradaController.java
src/main/java/org/springframework/samples/petclinic/web/UsuarioController.java
src/main/java/org/springframework/samples/petclinic/web/UsuarioValidator.java
src/main/resources/db/hsqldb/data.sql
src/main/resources/messages/messages.properties
src/main/webapp/WEB-INF/jsp/about.jsp
src/test/java/org/springframework/samples/petclinic/model/EntradaValidatorTest.java

hechas validaciones para que no se pueda repetir ni el dni, ni el
usuario ni su correo

Validaciones usuario atributos repetidos

---

src/main/java/org/springframework/samples/petclinic/web/FestivalController.java
src/main/webapp/WEB-INF/jsp/festivales/cartel.jsp
src/main/webapp/WEB-INF/jsp/festivales/festivalListing.jsp

Añadido el cartel de artistas desde user y sponsor

Añadido el cartel de artistas desde user y sponsor

---

src/main/java/org/springframework/samples/petclinic/model/BaseEntity.java
src/main/java/org/springframework/samples/petclinic/web/ArtistaController.java
src/main/java/org/springframework/samples/petclinic/web/ConcertController.java
src/main/java/org/springframework/samples/petclinic/web/EntradaController.java
src/main/java/org/springframework/samples/petclinic/web/FestivalController.java
src/main/java/org/springframework/samples/petclinic/web/PuestoController.java
src/main/java/org/springframework/samples/petclinic/web/RecintoController.java
src/main/resources/db/hsqldb/data.sql
src/main/webapp/WEB-INF/jsp/artistas/createOrUpdateArtistaForm.jsp
src/main/webapp/WEB-INF/jsp/concerts/createOrUpdateConcertForm.jsp
src/main/webapp/WEB-INF/jsp/entradas/createOrUpdateEntradaForm.jsp
src/main/webapp/WEB-INF/jsp/festivales/createOrUpdateFestivalForm.jsp
src/main/webapp/WEB-INF/jsp/puestos/createOrUpdatePuestoForm.jsp
src/main/webapp/WEB-INF/jsp/recintos/createOrUpdateRecintoForm.jsp

Añadido versionado a todas las entidades. Comentados los métodos de

---

HOME_LOG_IS_UNDEFINED
logs/SPRING-BOOT-LOGGER.LOG
logs/app.log
pom.xml
src/main/java/org/springframework/samples/petclinic/PetclinicApplication.java
src/main/java/org/springframework/samples/petclinic/web/ArtistaController.java
src/main/java/org/springframework/samples/petclinic/web/ConcertController.java
src/main/java/org/springframework/samples/petclinic/web/PuestoController.java
src/main/resources/application.properties
src/main/resources/logback.xml

He creado logs en los controladores de artista, puesto y concierto

Buenas prácticas: Logs

---

src/main/java/org/springframework/samples/petclinic/service/ConcertService.java
src/main/java/org/springframework/samples/petclinic/service/FestivalService.java
src/main/java/org/springframework/samples/petclinic/service/OfertaService.java
src/main/java/org/springframework/samples/petclinic/service/OpinionService.java
src/main/java/org/springframework/samples/petclinic/service/RecintoService.java
src/test/java/org/springframework/samples/petclinic/web/ConcertControllerTests.java

Añadido en servicios de Concierto, Opinion y Oferta.

Añadido algunos @Transactional en ciertos métodos de servicio

---

src/main/java/org/springframework/samples/springfest/web/UsuarioController.java
src/test/java/org/springframework/samples/springfest/web/UsuarioControllerTests.java

Ya funciona el test de subir usuario con errores.

Arreglo de los test de controlador de usuario

---

src/main/java/org/springframework/samples/springfest/service/PuestoService.java
src/main/java/org/springframework/samples/springfest/service/RecintoService.java
src/main/webapp/WEB-INF/jsp/entradas/detallesEntrada.jsp
src/main/webapp/WEB-INF/jsp/entradas/entradaListing.jsp
src/main/webapp/WEB-INF/jsp/entradas/misEntradasCompradas.jsp

Añadidas las anotaciones de transactional en los servicios de puesto y
recinto que faltaban.

Realizadas correciones esteticas en la compra de entradas.

---

src/main/java/org/springframework/samples/springfest/web/PuestoController.java
src/test/java/org/springframework/samples/springfest/web/PuestoControllerTest.java
src/test/java/org/springframework/samples/springfest/web/RecintoControllerTest.java

Intentadas las pruebas de controlador de puesto sin éxito.

Arreglados algunos fallos en RecintoControllerTest

---

src/test/java/org/springframework/samples/springfest/model/OpinionValidatorTest.java
src/test/java/org/springframework/samples/springfest/service/PuestoServiceTest.java

Añadidas las pruebas de servicio de puesto, que siguen sin ir sin saber
por qué.

Cambiado error en pruebas de OpinionValidator.

---

src/main/java/org/springframework/samples/springfest/service/OfertaService.java
src/test/java/org/springframework/samples/springfest/model/OpinionValidatorTest.java
src/test/java/org/springframework/samples/springfest/web/ArtistControllerSecurityTest.java
src/test/java/org/springframework/samples/springfest/web/FestivalControllerTest.java
src/test/java/org/springframework/samples/springfest/web/OfertaControllerTests.java

Controller Test oferta y fest / Prueba EndToEnd artist security - minicorreción

Manuel sprint4pruebas

---

src/main/java/org/springframework/samples/springfest/web/OfertaController.java
src/test/java/org/springframework/samples/springfest/web/FestivalControllerTest.java
src/test/java/org/springframework/samples/springfest/web/RecintoControllerTest.java

Correcciones en test y controller de oferta y recinto

MiniCorrección controller oferta y test de controlador.

---

src/main/java/org/springframework/samples/springfest/service/FestivalService.java
src/main/java/org/springframework/samples/springfest/service/OfertaService.java
src/main/java/org/springframework/samples/springfest/web/FestivalController.java
src/main/java/org/springframework/samples/springfest/web/OfertaController.java
src/main/webapp/WEB-INF/jsp/entradas/entradaListing.jsp
src/main/webapp/WEB-INF/jsp/festivales/vistaFestival.jsp
src/main/webapp/WEB-INF/jsp/ofertas/ofertaListing.jsp
src/test/java/org/springframework/samples/springfest/service/OfertaServiceTests.java

Ya no se puede borrar una entrada ni una oferta, ya que había conflictos
cuando un usuario había comprado esa entrada.

Arreglo de borrar entrada y oferta
